name: ROS2 Integration Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v3
      - name: build and test
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Build workspace
        run: |
          mkdir -p ros2_ws/src
          cp -r ros2_ws/src/speed_lim_pkg
          cd ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build

      - name: Run integration test
        run: |
          cd ros2_ws
          source install/setup.bash
          bash src/speed_lim_pkg/test/test.bash

